name: opentok_flutter
description: Flutter library for OpenTok iOS and Android SDKs
version: 0.0.1
author: null
homepage: null

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutterbr.opentok_flutter
        pluginClass: OpenTokFlutterPlugin
      ios:
        pluginClass: OpenTokFlutterPlugin
